dpo:
  sft_adapter_path: "outputs/sft/qwen3_4b_sft_final_jang"

  trainer:
    output_dir: "outputs/dpo/qwen3_4b_dpo_final_jang_v1"

    num_train_epochs: 1
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 1
    gradient_accumulation_steps: 4

    learning_rate: 0.0000005
    lr_scheduler_type: "cosine"
    warmup_ratio: 0.1

    beta: 0.3
    label_smoothing: 0.0
    loss_type: "ipo"

    fp16: true
    bf16: false

    eval_strategy: "steps"
    save_strategy: "steps"
    logging_steps: 50
    eval_steps: 50
    save_steps: 100

    load_best_model_at_end: true
    metric_for_best_model: "eval_rewards/accuracies"
    greater_is_better: true
    save_total_limit: 2

    max_length: 2048
    max_prompt_length: 1820
    max_completion_length: 1000

    remove_unused_columns: false
    report_to: "wandb"
    seed: 42

  data:
    train_path: "/data/ephemeral/pro-nlp-finalproject-nlp-13/data/persona_data/dpo_dataset/dpo_train_dataset_v2.json"
    seed: 42
    csv_dir: "./data/dpo_outputs"
    margin_threshold: 0.995
    eval_ratio: 0.1


model:
  model_name_or_path: "Qwen/Qwen3-4B-Instruct-2507"
  compute_dtype: "float16"
  device_map: "auto"
  use_gradient_checkpointing: true
  trust_remote_code: true


wandb:
  enabled: true
  run_name: "qwen_dpo_v6_multi_1"
  project: "DPO-qwen-debug-normal"
  entity: "pro-nlp-final-13"
  dir: "./wandb"