embedding:
  file_path: ["data/crawling/sports_crawling.csv", "data/crawling/stay_crawling.csv", "data/guidebook/busan_rag_data.json"]
  model_name: "solar-embedding-1-large"
db_path: "src/results/db/chroma_db"
bm25_path: "src/results/db/bm25"