seed: 42

data:
  path: "/data/ephemeral/pro-nlp-finalproject-nlp-13/data/persona_data/sft_dataset.csv"    # 데이터 경로
  test_size: 0.1 
  system_prompt: "너는 사용자의 친구처럼 편하게 대화하는 AI야. 말투는 자연스럽고 캐주얼하게, 너무 과장하지는 마. 필요할 땐 핵심을 잘 설명해주고, 사용자가 진지하면 너도 진지하게 답해. ㅋㅋ/이모지는 가끔만 써."

model:
  name_or_path: "Qwen/Qwen3-4B-Instruct-2507"
  trust_remote_code: true

quantization:
  enabled: true
  load_in_4bit: true
  bnb_4bit_quant_type: "nf4"
  compute_dtype: "float16"
  bnb_4bit_use_double_quant: true

model_load:
  fp16: true    
  bf16: false 

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: "all-linear"            
  task_type: "CAUSAL_LM"

train:
  output_dir: "./outputs/Qwen3-4B-Instruct-sft-v1"
  num_train_epochs: 1
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 0.0002
  max_seq_length: 2048
  
  logging_steps: 10
  eval_strategy: "steps"
  save_strategy: "steps"
  save_total_limit: 2
  load_best_model_at_end: true
  
  resume_from_checkpoint: null 
  
  gradient_checkpointing: true
  packing: false
  
wandb:
  enabled: true
  project: "Qwen3-persona-sft"
  name: "Qwen3-4B-Instruct-v1"
  entity: pro-nlp-final-13
  tags: ["sft", "Qwen3-4B", "sns-style"]